image: maven:3.3.9-jdk-8
build:
  script:
    - mvn compile

    
test:
  script:
    - mvn install -B
  artifacts:
    name: "MAVEN"
    paths:
      - ./RunTests.bat
      
include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml